### ISSUE TITLE
syntax error with extraneous commas

### ISSUE THREAD

**Issue by Beliavsky** [lievertom/date_Fortran#1]
Compiling mydate.f90 with gfortran I get two errors which can be fixed by removing commas:

mydate.f90:134:16:

  134 |         print *,
      |                1
Error: Comma after * at (1) not allowed without I/O list
mydate.f90:189:24:

  189 |                 print *,
      |                        1
Error: Comma after * at (1) not allowed without I/O list

**Comment by lievertom** [comment]
The error was corrected only by removing the commas, for some reason here it did not present this compilation error, thanks for the collaboration!
